#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v13
# autospec commit: 2659038
#
Name     : R-tidyrules
Version  : 0.2.7
Release  : 14
URL      : https://cran.r-project.org/src/contrib/tidyrules_0.2.7.tar.gz
Source0  : https://cran.r-project.org/src/contrib/tidyrules_0.2.7.tar.gz
Summary  : Utilities to Retrieve Rulelists from Model Fits, Filter, Prune,
Group    : Development/Tools
License  : GPL-3.0
Requires: R-DescTools
Requires: R-MetricsWeighted
Requires: R-checkmate
Requires: R-cli
Requires: R-data.table
Requires: R-generics
Requires: R-glue
Requires: R-magrittr
Requires: R-partykit
Requires: R-pheatmap
Requires: R-proxy
Requires: R-purrr
Requires: R-rlang
Requires: R-stringr
Requires: R-tibble
Requires: R-tidytable
BuildRequires : R-AmesHousing
BuildRequires : R-C50
BuildRequires : R-DescTools
BuildRequires : R-MetricsWeighted
BuildRequires : R-checkmate
BuildRequires : R-cli
BuildRequires : R-data.table
BuildRequires : R-generics
BuildRequires : R-glue
BuildRequires : R-magrittr
BuildRequires : R-mlbench
BuildRequires : R-modeldata
BuildRequires : R-palmerpenguins
BuildRequires : R-partykit
BuildRequires : R-pheatmap
BuildRequires : R-proxy
BuildRequires : R-purrr
BuildRequires : R-rlang
BuildRequires : R-stringr
BuildRequires : R-tibble
BuildRequires : R-tidytable
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# tidyrules
<!-- badges: start -->
[![CRAN_Status_Badge](https://www.r-pkg.org/badges/version/tidyrules)](https://cran.r-project.org/package=tidyrules)
<!-- badges: end -->

%prep
%setup -q -n tidyrules
pushd ..
cp -a tidyrules buildavx2
popd
pushd ..
cp -a tidyrules buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720120249

%install
export SOURCE_DATE_EPOCH=1720120249
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tidyrules/DESCRIPTION
/usr/lib64/R/library/tidyrules/INDEX
/usr/lib64/R/library/tidyrules/Meta/Rd.rds
/usr/lib64/R/library/tidyrules/Meta/features.rds
/usr/lib64/R/library/tidyrules/Meta/hsearch.rds
/usr/lib64/R/library/tidyrules/Meta/links.rds
/usr/lib64/R/library/tidyrules/Meta/nsInfo.rds
/usr/lib64/R/library/tidyrules/Meta/package.rds
/usr/lib64/R/library/tidyrules/NAMESPACE
/usr/lib64/R/library/tidyrules/NEWS.md
/usr/lib64/R/library/tidyrules/R/tidyrules
/usr/lib64/R/library/tidyrules/R/tidyrules.rdb
/usr/lib64/R/library/tidyrules/R/tidyrules.rdx
/usr/lib64/R/library/tidyrules/help/AnIndex
/usr/lib64/R/library/tidyrules/help/aliases.rds
/usr/lib64/R/library/tidyrules/help/figures/tidyrules_schematic.png
/usr/lib64/R/library/tidyrules/help/paths.rds
/usr/lib64/R/library/tidyrules/help/tidyrules.rdb
/usr/lib64/R/library/tidyrules/help/tidyrules.rdx
/usr/lib64/R/library/tidyrules/html/00Index.html
/usr/lib64/R/library/tidyrules/html/R.css
/usr/lib64/R/library/tidyrules/tests/testthat.R
/usr/lib64/R/library/tidyrules/tests/testthat/test-c5.R
/usr/lib64/R/library/tidyrules/tests/testthat/test-cubist.R
/usr/lib64/R/library/tidyrules/tests/testthat/test-party.R
/usr/lib64/R/library/tidyrules/tests/testthat/test-rpart.R
/usr/lib64/R/library/tidyrules/tests/testthat/test-rulelist.R
